# Deployment of prometheus on cluster
---
# Create Namespace monitoring
apiVersion: v1
kind: Namespace
metadata:
  name: monitoring
---
# CONFIGMAP of the deployment
apiVersion: v1
kind: ConfigMap
metadata:
  name: prometheus-server-conf
  labels:
    name: prometheus-server-conf
  namespace: monitoring
data:
  prometheus.yml: |
    global:
      scrape_interval: 10s


---
# Clusterrole that allows get, listing, watching, on apigroups
apiVersion: rbac.authorization.k8s.io/v1beta1`
kind: ClusterRole
metadata:
  name: prometheus-role
rules:
- apiGroups: [""]
  resources:
  - nodes
  - services
  - endpoints
  - pods
  verbs: ["get", "list", "watch"]
- apiGroups:
  - extensions
  resources:
  - ingresses
  verbs: ["get", "list", "watch"]
- nonResourceURLs: ["/metrics"]
  verbs: ["get"]
---
# Service account
apiVersion: v1
kind: ServiceAccount
metadata:
  name: prometheus-service
  namespace: monitoring
---
# Binding cluster role to service account
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRoleBinding
metadata:
  name: prometheus-binding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: prometheus-role
subjects:
- kind: ServiceAccount
  name: prometheus-service
  namespace: monitoring
---
