---
- name: Copy K3s service file
  template:
    src: "templates/k3s.service.worker.j2"
    dest: "/etc/systemd/system/k3s-node.service"
    owner: root
    group: root
    mode: 0755

- name: Enable and check K3s service
  systemd:
    name: k3s-node
    daemon_reload: true
    state: restarted
    enabled: true
