---
- name: Setup autoupdates
  apt:
    pkg: unattended-upgrades
    state: present
    update_cache: true

- name: create unattended-upgrades configuration
  template:
    src: "{{ item }}.j2"
    dest: "/etc/apt/apt.conf.d/{{ item }}"
    owner: root
    group: root
    mode: 0644
  with_items:
    - 10periodic
    - 50unattended-upgrades

- name: Ensure auto updates are running
  service:
    name: unattended-upgrades
    state: started
    enabled: true
  when: not ansible_check_mode
