---
- name: Set hostname of cluster
  hostname:
    name: "{{ inventory_hostname }}"
    use: debian

- name: Configure /etc/hosts file
  template:
    src: "templates/hosts.j2"
    dest: "/etc/hosts"
    owner: root
    group: root
    mode: 0644
